### Extract Data

In [2]:
import requests

In [33]:
list_of_cities = []

In [35]:
cities = [
    "Cairo",
    "Giza",
    "Alexandria",
    "Port Said",
    "Suez",
    "Ismailia",
    "Mansoura",
    "Tanta",
    "Luxor",
    "Aswan"
]

In [ ]:
url = "https://api.openweathermap.org/data/2.5/weather"

params = {
    "appid": "6a13e61e853763292101962a026aa3e8",
    "q": "Giza"
    
}

response = requests.get(url, params=params)

data = response.json()
data

In [36]:
for city in cities:
    print(city)
    params = {
    "appid": "6a13e61e853763292101962a026aa3e8",
    "q": city
    }
    response = requests.get(url, params=params)
    data = response.json()
    city = city
    country = 'Egypt'
    lat = data['coord']['lat']
    lon = data['coord']['lon']
    temp = data['main']['temp']
    pressure = data['main']['pressure']
    Humidity = data['main']['humidity']
    wind_speed = data['wind']['speed']
 
 
    list_of_cities.append({
        'city': city,
        'country': country,
        'lat': lat,
        'lon': lon,
        'temp': temp,
        'pressure': pressure,
        'humidity': Humidity,
        'wind_speed': wind_speed
    })

Cairo
Giza
Alexandria
Port Said
Suez
Ismailia
Mansoura
Tanta
Luxor
Aswan

In [37]:
list_of_cities

[{'city': 'Cairo',
  'country': 'Egypt',
  'lat': 30.0626,
  'lon': 31.2497,
  'temp': 305.57,
  'pressure': 1012,
  'humidity': 31,
  'wind_speed': 4.12},
 {'city': 'Giza',
  'country': 'Egypt',
  'lat': 30.0081,
  'lon': 31.2109,
  'temp': 305.56,
  'pressure': 1012,
  'humidity': 30,
  'wind_speed': 3.33},
 {'city': 'Alexandria',
  'country': 'Egypt',
  'lat': 31.2156,
  'lon': 29.9553,
  'temp': 301.13,
  'pressure': 1014,
  'humidity': 57,
  'wind_speed': 4.63},
 {'city': 'Port Said',
  'country': 'Egypt',
  'lat': 31.2565,
  'lon': 32.2841,
  'temp': 303.14,
  'pressure': 1012,
  'humidity': 58,
  'wind_speed': 5.66},
 {'city': 'Suez',
  'country': 'Egypt',
  'lat': 29.9737,
  'lon': 32.5263,
  'temp': 305.97,
  'pressure': 1011,
  'humidity': 29,
  'wind_speed': 4.37},
 {'city': 'Ismailia',
  'country': 'Egypt',
  'lat': 30.6043,
  'lon': 32.2723,
  'temp': 306.19,
  'pressure': 1011,
  'humidity': 40,
  'wind_speed': 5.66},
 {'city': 'Mansoura',
  'country': 'Egypt',
  'lat': 34.8616,
  'lon': -1.3394,
  'temp': 294.94,
  'pressure': 1014,
  'humidity': 57,
  'wind_speed': 2.06},
 {'city': 'Tanta',
  'country': 'Egypt',
  'lat': 30.7885,
  'lon': 31.0019,
  'temp': 305.96,
  'pressure': 1012,
  'humidity': 28,
  'wind_speed': 4.79},
 {'city': 'Luxor',
  'country': 'Egypt',
  'lat': 25.6989,
  'lon': 32.6421,
  'temp': 312.18,
  'pressure': 1010,
  'humidity': 18,
  'wind_speed': 3.09},
 {'city': 'Aswan',
  'country': 'Egypt',
  'lat': 24.0934,
  'lon': 32.907,
  'temp': 312.76,
  'pressure': 1009,
  'humidity': 17,
  'wind_speed': 6.69}]

In [10]:
import pandas as pd

In [38]:
df = pd.DataFrame(list_of_cities)
df

,city,country,lat,lon,temp,pressure,humidity,wind_speed
0,Cairo,Egypt,30.0626,31.2497,305.57,1012,31,4.12
1,Giza,Egypt,30.0081,31.2109,305.56,1012,30,3.33
2,Alexandria,Egypt,31.2156,29.9553,301.13,1014,57,4.63
3,Port Said,Egypt,31.2565,32.2841,303.14,1012,58,5.66
4,Suez,Egypt,29.9737,32.5263,305.97,1011,29,4.37
5,Ismailia,Egypt,30.6043,32.2723,306.19,1011,40,5.66
6,Mansoura,Egypt,34.8616,-1.3394,294.94,1014,57,2.06
7,Tanta,Egypt,30.7885,31.0019,305.96,1012,28,4.79
8,Luxor,Egypt,25.6989,32.6421,312.18,1010,18,3.09
9,Aswan,Egypt,24.0934,32.9070,312.76,1009,17,6.69

In [47]:
def fun1(city):
    if city == 'Cairo':
        return 'Greater Cairo'
    elif city == 'Giza':
        return 'Greater Cairo'
    elif city == 'Alexandria':
        return 'North Coast'
    elif city == 'Port Said':
        return 'North Coast'
    elif city == 'Suez':
        return 'Canal'
    elif city == 'Ismailia':
        return 'Canal'
    elif city == 'Mansoura':
        return 'Delta'
    elif city == 'Tanta':
        return 'Delta'
    elif city == 'Luxor':
        return 'Lower Egypt'
    elif city == 'Aswan':
        return 'Lower Egypt'

In [49]:
df['Region']= df['city'].apply(fun1)
df

,city,country,lat,lon,temp,pressure,humidity,wind_speed,temp_celsius,Region
0,Cairo,Egypt,30.0626,31.2497,305.57,1012,31,4.12,32.57,Greater Cairo
1,Giza,Egypt,30.0081,31.2109,305.56,1012,30,3.33,32.56,Greater Cairo
2,Alexandria,Egypt,31.2156,29.9553,301.13,1014,57,4.63,28.13,North Coast
3,Port Said,Egypt,31.2565,32.2841,303.14,1012,58,5.66,30.14,North Coast
4,Suez,Egypt,29.9737,32.5263,305.97,1011,29,4.37,32.97,Canal
5,Ismailia,Egypt,30.6043,32.2723,306.19,1011,40,5.66,33.19,Canal
6,Mansoura,Egypt,34.8616,-1.3394,294.94,1014,57,2.06,21.94,Delta
7,Tanta,Egypt,30.7885,31.0019,305.96,1012,28,4.79,32.96,Delta
8,Luxor,Egypt,25.6989,32.6421,312.18,1010,18,3.09,39.18,Lower Egypt
9,Aswan,Egypt,24.0934,32.9070,312.76,1009,17,6.69,39.76,Lower Egypt

In [50]:
df['temp_celsius'] = df['temp'].apply(lambda temp: temp - 273.0)
df

,city,country,lat,lon,temp,pressure,humidity,wind_speed,temp_celsius,Region
0,Cairo,Egypt,30.0626,31.2497,305.57,1012,31,4.12,32.57,Greater Cairo
1,Giza,Egypt,30.0081,31.2109,305.56,1012,30,3.33,32.56,Greater Cairo
2,Alexandria,Egypt,31.2156,29.9553,301.13,1014,57,4.63,28.13,North Coast
3,Port Said,Egypt,31.2565,32.2841,303.14,1012,58,5.66,30.14,North Coast
4,Suez,Egypt,29.9737,32.5263,305.97,1011,29,4.37,32.97,Canal
5,Ismailia,Egypt,30.6043,32.2723,306.19,1011,40,5.66,33.19,Canal
6,Mansoura,Egypt,34.8616,-1.3394,294.94,1014,57,2.06,21.94,Delta
7,Tanta,Egypt,30.7885,31.0019,305.96,1012,28,4.79,32.96,Delta
8,Luxor,Egypt,25.6989,32.6421,312.18,1010,18,3.09,39.18,Lower Egypt
9,Aswan,Egypt,24.0934,32.9070,312.76,1009,17,6.69,39.76,Lower Egypt

In [51]:
def fun2 (temp_celsius):
    if temp_celsius < 30 :
       return 'Cold'
    elif temp_celsius < 34 :
       return 'Moderate'
    else :
       return 'Hot'

In [52]:
df['TemperatureCategory'] = df['temp_celsius'].apply(fun2)
df

,city,country,lat,lon,temp,pressure,humidity,wind_speed,temp_celsius,Region,TemperatureCategory
0,Cairo,Egypt,30.0626,31.2497,305.57,1012,31,4.12,32.57,Greater Cairo,Moderate
1,Giza,Egypt,30.0081,31.2109,305.56,1012,30,3.33,32.56,Greater Cairo,Moderate
2,Alexandria,Egypt,31.2156,29.9553,301.13,1014,57,4.63,28.13,North Coast,Cold
3,Port Said,Egypt,31.2565,32.2841,303.14,1012,58,5.66,30.14,North Coast,Moderate
4,Suez,Egypt,29.9737,32.5263,305.97,1011,29,4.37,32.97,Canal,Moderate
5,Ismailia,Egypt,30.6043,32.2723,306.19,1011,40,5.66,33.19,Canal,Moderate
6,Mansoura,Egypt,34.8616,-1.3394,294.94,1014,57,2.06,21.94,Delta,Cold
7,Tanta,Egypt,30.7885,31.0019,305.96,1012,28,4.79,32.96,Delta,Moderate
8,Luxor,Egypt,25.6989,32.6421,312.18,1010,18,3.09,39.18,Lower Egypt,Hot
9,Aswan,Egypt,24.0934,32.9070,312.76,1009,17,6.69,39.76,Lower Egypt,Hot

In [53]:
def fun3 (humidity):
    if humidity < 30 :
       return 'Low'
    elif humidity < 40 :
       return 'Medium'
    else :
       return 'High'

In [54]:
df['HumidityCategory'] = df['humidity'].apply(fun3)
df

,city,country,lat,lon,temp,pressure,humidity,wind_speed,temp_celsius,Region,TemperatureCategory,HumidityCategory
0,Cairo,Egypt,30.0626,31.2497,305.57,1012,31,4.12,32.57,Greater Cairo,Moderate,Medium
1,Giza,Egypt,30.0081,31.2109,305.56,1012,30,3.33,32.56,Greater Cairo,Moderate,Medium
2,Alexandria,Egypt,31.2156,29.9553,301.13,1014,57,4.63,28.13,North Coast,Cold,High
3,Port Said,Egypt,31.2565,32.2841,303.14,1012,58,5.66,30.14,North Coast,Moderate,High
4,Suez,Egypt,29.9737,32.5263,305.97,1011,29,4.37,32.97,Canal,Moderate,Low
5,Ismailia,Egypt,30.6043,32.2723,306.19,1011,40,5.66,33.19,Canal,Moderate,High
6,Mansoura,Egypt,34.8616,-1.3394,294.94,1014,57,2.06,21.94,Delta,Cold,High
7,Tanta,Egypt,30.7885,31.0019,305.96,1012,28,4.79,32.96,Delta,Moderate,Low
8,Luxor,Egypt,25.6989,32.6421,312.18,1010,18,3.09,39.18,Lower Egypt,Hot,Low
9,Aswan,Egypt,24.0934,32.9070,312.76,1009,17,6.69,39.76,Lower Egypt,Hot,Low

In [ ]:
from datetime import date, datetime


date = datetime.now()

In [59]:
import pyodbc

In [68]:
df

,city,country,lat,lon,temp,pressure,humidity,wind_speed,temp_celsius,Region,TemperatureCategory,HumidityCategory
0,Cairo,Egypt,30.0626,31.2497,305.57,1012,31,4.12,32.57,Greater Cairo,Moderate,Medium
1,Giza,Egypt,30.0081,31.2109,305.56,1012,30,3.33,32.56,Greater Cairo,Moderate,Medium
2,Alexandria,Egypt,31.2156,29.9553,301.13,1014,57,4.63,28.13,North Coast,Cold,High
3,Port Said,Egypt,31.2565,32.2841,303.14,1012,58,5.66,30.14,North Coast,Moderate,High
4,Suez,Egypt,29.9737,32.5263,305.97,1011,29,4.37,32.97,Canal,Moderate,Low
5,Ismailia,Egypt,30.6043,32.2723,306.19,1011,40,5.66,33.19,Canal,Moderate,High
6,Mansoura,Egypt,34.8616,-1.3394,294.94,1014,57,2.06,21.94,Delta,Cold,High
7,Tanta,Egypt,30.7885,31.0019,305.96,1012,28,4.79,32.96,Delta,Moderate,Low
8,Luxor,Egypt,25.6989,32.6421,312.18,1010,18,3.09,39.18,Lower Egypt,Hot,Low
9,Aswan,Egypt,24.0934,32.9070,312.76,1009,17,6.69,39.76,Lower Egypt,Hot,Low

In [69]:
data = list(df.itertuples(index=False, name=None))

In [66]:
import pyodbc

conn = pyodbc.connect(
    "driver={ODBC Driver 17 for SQL Server};"
    "server=depi12462.database.windows.net;"
    "database=Depi;"
    "UID=sqladmin;"
    "PWD=Depi123#;"
)

cursor = conn.cursor()

cursor.execute("""
create table Anas_Ahmed (
    city VARCHAR(50),
    country VARCHAR(50),
    lat VARCHAR(50),
    lon VARCHAR(50),
    temp VARCHAR(50),
    pressure VARCHAR(50),
    humidity VARCHAR(50),
    wind_speed VARCHAR(50),
    Region VARCHAR(50),
    temp_celsius VARCHAR(50),
    TemperatureCategory VARCHAR(50),
    HumidityCategory VARCHAR(50)
)
""")

conn.commit()
cursor.close()
conn.close()

In [74]:
df

,city,country,lat,lon,temp,pressure,humidity,wind_speed,temp_celsius,Region,TemperatureCategory,HumidityCategory
0,Cairo,Egypt,30.0626,31.2497,305.57,1012,31,4.12,32.57,Greater Cairo,Moderate,Medium
1,Giza,Egypt,30.0081,31.2109,305.56,1012,30,3.33,32.56,Greater Cairo,Moderate,Medium
2,Alexandria,Egypt,31.2156,29.9553,301.13,1014,57,4.63,28.13,North Coast,Cold,High
3,Port Said,Egypt,31.2565,32.2841,303.14,1012,58,5.66,30.14,North Coast,Moderate,High
4,Suez,Egypt,29.9737,32.5263,305.97,1011,29,4.37,32.97,Canal,Moderate,Low
5,Ismailia,Egypt,30.6043,32.2723,306.19,1011,40,5.66,33.19,Canal,Moderate,High
6,Mansoura,Egypt,34.8616,-1.3394,294.94,1014,57,2.06,21.94,Delta,Cold,High
7,Tanta,Egypt,30.7885,31.0019,305.96,1012,28,4.79,32.96,Delta,Moderate,Low
8,Luxor,Egypt,25.6989,32.6421,312.18,1010,18,3.09,39.18,Lower Egypt,Hot,Low
9,Aswan,Egypt,24.0934,32.9070,312.76,1009,17,6.69,39.76,Lower Egypt,Hot,Low

In [77]:
import pyodbc

conn = pyodbc.connect(
    "driver={ODBC Driver 17 for SQL Server};"
    "server=depi12462.database.windows.net;"
    "database=Depi;"
    "UID=sqladmin;"
    "PWD=Depi123#;"
)

cursor = conn.cursor()

cursor.executemany("""
    INSERT INTO Anas_Ahmed
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
""", data)

conn.commit()

cursor.close()
conn.close()

In [76]:
data

[('Cairo',
  'Egypt',
  30.0626,
  31.2497,
  305.57,
  1012,
  31,
  4.12,
  32.56999999999999,
  'Greater Cairo',
  'Moderate',
  'Medium'),
 ('Giza',
  'Egypt',
  30.0081,
  31.2109,
  305.56,
  1012,
  30,
  3.33,
  32.56,
  'Greater Cairo',
  'Moderate',
  'Medium'),
 ('Alexandria',
  'Egypt',
  31.2156,
  29.9553,
  301.13,
  1014,
  57,
  4.63,
  28.129999999999995,
  'North Coast',
  'Cold',
  'High'),
 ('Port Said',
  'Egypt',
  31.2565,
  32.2841,
  303.14,
  1012,
  58,
  5.66,
  30.139999999999986,
  'North Coast',
  'Moderate',
  'High'),
 ('Suez',
  'Egypt',
  29.9737,
  32.5263,
  305.97,
  1011,
  29,
  4.37,
  32.97000000000003,
  'Canal',
  'Moderate',
  'Low'),
 ('Ismailia',
  'Egypt',
  30.6043,
  32.2723,
  306.19,
  1011,
  40,
  5.66,
  33.19,
  'Canal',
  'Moderate',
  'High'),
 ('Mansoura',
  'Egypt',
  34.8616,
  -1.3394,
  294.94,
  1014,
  57,
  2.06,
  21.939999999999998,
  'Delta',
  'Cold',
  'High'),
 ('Tanta',
  'Egypt',
  30.7885,
  31.0019,
  305.96,
  1012,
  28,
  4.79,
  32.95999999999998,
  'Delta',
  'Moderate',
  'Low'),
 ('Luxor',
  'Egypt',
  25.6989,
  32.6421,
  312.18,
  1010,
  18,
  3.09,
  39.18000000000001,
  'Lower Egypt',
  'Hot',
  'Low'),
 ('Aswan',
  'Egypt',
  24.0934,
  32.907,
  312.76,
  1009,
  17,
  6.69,
  39.75999999999999,
  'Lower Egypt',
  'Hot',
  'Low')]